### ISSUE TITLE
Dead link for OE guidelines

### ISSUE THREAD

**Issue by Fefaine** [openeuropa/documentation#51]
Hello,

I am browsing https://github.com/openeuropa/documentation for contribution guidelines.
I follow "Contribution workflow" link to https://github.com/openeuropa/documentation/blob/master/docs/initiative/contribution-workflow.md
Then I follow "OpenEuropa contribution guidelines." which is a dead link

**Comment by hernani** [comment]
Fixed in https://github.com/openeuropa/documentation/pull/53
