### ISSUE TITLE
Question: versioning policy + official installation guide not accurate

### ISSUE THREAD

**Issue by stijn-dejongh** [openeuropa/documentation#56]
Dear OpenEuropa team.

Could you direct me to your policy for versioning of the Open Europa ecosystem, 
or to a master composer file with compatible and stable library versions?

It seems to me that you include dependencies on active branches in stead of stable release versions, even when the top artifact is considered a stable release (e.g. OpenEurope Theme v 2.9.0).
I have a local environment, that is shared through docker with my team. Earlier this week, I ran the "composer update" command as I wanted to update the version of a few drupal core package (default-content, and others).
Unfortunately, this also pulled in the latest version of oe_content and oe_media,  which depend on dev-master dependencies down the line. 

This broke my installation. It seems to me that the only way to avoid this issue from a user's perspective is to never update the composer.lock file or external libraries once the deployment is working.

I am currently following the suggested approach for installation (using composer require) and am still running in to compatibility issues, as I am unable to start the oe_theme_news module due to missing internal dependencies.

Composer file for reference, created using 'composer require'.
I added the consolidation packages manually, as I was getting errors at installation time for missing dependencies.
[composer_not_working.txt](https://github.com/openeuropa/documentation/files/5339412/composer_not_working.txt)

When I run the installer without locally building the latest banch of oe_theme, and just rely on the
require approach you would use with other themes, this is how my deployment ends up looking:

![oe_theme_issue](https://user-images.githubusercontent.com/25401297/95311461-f04e3400-088d-11eb-8af8-a0c74b76eb3c.png)

Any help addressing this issue is appreciated.
For now I will direct my efforts to forking and building oe_theme myself as part of my setup script.

Kind regards,

Stijn

**Comment by brummbar** [comment]
Hello @justDoji , can you provide us some more information regarding which dependencies are missing?
Regarding oe_theme/oe_content, which sub-modules have you enabled?

**Comment by justDoji** [comment]
Dear @brummbar,

Here is my runner.yml file `drush en` section.
I removed the `en oe_theme_events' command, as this was causing a failure that stopped the build process.

[runner_operations.txt](https://github.com/openeuropa/documentation/files/5340504/runner_operations.txt)

**Comment by ademarco** [comment]
Hello @stijn-dejongh , unfortunately that's an open question, within the OpenEuropa team too. The best we could come up with at the moment is:

- When dependencies are required by a sub-module (and not by the main module) we make sure we specify it in that sub-module's README.md (please let us know if you still find missing info, we might have missed some sub-modules)
- On the site using the OpenEuropa module we lock it to the minor, so we can better govern the update process. This is what we do in the distro we are building using our components:

```
...
        "openeuropa/oe_list_pages": "~0.2.0",
        "openeuropa/oe_media": "~1.9.0",
        "openeuropa/oe_multilingual": "~1.5.0",
        "openeuropa/oe_paragraphs": "~1.6.0",
        "openeuropa/oe_search": "~1.5.0",
        "openeuropa/oe_theme": "~2.10.2",
        "openeuropa/oe_translation": "~0.9.0",
        "openeuropa/oe_webtools": "~1.8.0",
...
```

I guess we will have to specifically write it down on the OpenEuropa documentation too.

**Comment by ademarco** [comment]
Closing, as we are now listing required dependencies in sub-module's README files.
